

services:
  bot:
    build: .
    container_name: ship_ai
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_KEY=${API_KEY}
      - CHANNEL_NAME=${CHANNEL_NAME}
      - MODEL=${MODEL}
      - DATABASE_FILE=${DATABASE_FILE}
    networks:
      - bot_network
    env_file:
      - .env
    volumes:
      - ./images:/app/images
      - ./articles.db:/app/articles.db
    
networks:
  bot_network:
    driver: bridge